     - name: start duplicity container
       become: true
       docker_container:
         image: "datacoda/cron-duplicity"
         name: "duplicity"
         state: started
         pull: True
         restart_policy: always
         volumes:
           - /var/srv:/data
         env:
           AWS_ACCESS_KEY_ID="{{ lookup('hashi_vault', 'secret=secret/duplicity/aws-access-key-id:value') }}"
           AWS_SECRET_ACCESS_KEY="{{ lookup('hashi_vault', 'secret=secret/duplicity/aws-secret-access-key:value') }}"
           PASSPHRASE="{{ lookup('hashi_vault', 'secret=secret/duplicity/passphrase:value') }}"
           SOURCE_PATH="/data"
           REMOTE_URL="s3://sos-ch-dk-2.exo.io/pps-backup"
           PARAMS="--exclude /data/mysql --exclude /data/migration --exclude /data/migration-mysql"
