- name: start mariadb container
  become: true
  docker_container:
    image: "mariadb:10.4"
    name: "nextcloud-mysql"
    state: started
    restart_policy: always
    pull: True
    volumes:
      - /var/srv/mysql/nextcloud:/var/lib/mysql
    env:
      MYSQL_RANDOM_ROOT_PASSWORD="true"
      MYSQL_ONETIME_PASSWORD="true"
      MYSQL_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/nextcloud/mysql/password:value') }}"
      MYSQL_USER="nextcloud"
      MYSQL_DATABASE="nextcloud"

- name: start redis container
  become: true
  docker_container:
    image: "redis:alpine"
    name: "nextcloud-redis"
    state: started
    pull: True
    restart_policy: always

- name: start nextcloud container
  become: true
  docker_container:
    image: "nextcloud:18-apache"
    name: "nextcloud"
    labels:
     "traefik.enable": "true"
     "traefik.frontend.rule": "Host:cloud.piratenpartei.ch"
    state: started
    pull: True
    restart_policy: always
    links:
      - nextcloud-mysql:mysql
      - nextcloud-redis:redis
    volumes:
      - /var/srv/files/nextcloud/html:/var/www/html
      - /var/srv/files/nextcloud/data:/srv/data
    env:
      NEXTCLOUD_DATA_DIR=/srv/data
      NEXTCLOUD_UPDATE=1
      NEXTCLOUD_ADMIN_USER="admin"
      NEXTCLOUD_ADMIN_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/nextcloud/admin-pw/password:value') }}"
      MYSQL_HOST=mysql
      MYSQL_USER=nextcloud
      MYSQL_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/nextcloud/mysql/password:value') }}"
      MYSQL_DATABASE=nextcloud
      REDIS_HOST=redis
      SMTP_HOSTNAME="smtprelay.piratenpartei.ch"
      MAIL_FROM_ADDRESS="cloud@piratenpartei.ch"
      SMTP_PORT="25"

- name: start nextcloud cron container
  become: true
  docker_container:
    image: "nextcloud:18-apache"
    name: "nextcloud-cron"
    entrypoint: /cron.sh
    state: started
    pull: True
    restart_policy: always
    links:
      - nextcloud-mysql:mysql
      - nextcloud-redis:redis
    volumes:
      - /var/srv/files/nextcloud/html:/var/www/html
      - /var/srv/files/nextcloud/data:/srv/data
    env:
      NEXTCLOUD_DATA_DIR=/srv/data
      NEXTCLOUD_UPDATE=1
      NEXTCLOUD_ADMIN_USER=admin
      NEXTCLOUD_ADMIN_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/nextcloud/admin-pw/password:value') }}"
      MYSQL_HOST=mysql
      MYSQL_USER=nextcloud
      MYSQL_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/nextcloud/mysql/password:value') }}"
      MYSQL_DATABASE=nextcloud
      REDIS_HOST=redis
      SMTP_HOSTNAME="smtprelay.piratenpartei.ch"
      MAIL_FROM_ADDRESS="cloud@piratenpartei.ch"
      SMTP_PORT="25"

- name: start backup container for mariadb
  become: true
  docker_container:
    image: yloeffler/mysql-backup
    name: "nextcloud-backup"
    state: started
    restart_policy: always
    pull: True
    links:
      - nextcloud-mysql:mysql
    volumes:
      - /var/srv/mysql-backup/nextcloud:/backup
    env:
      MYSQL_PASS="{{ lookup('hashi_vault', 'secret=secret/nextcloud/mysql/password:value') }}"
      MAX_BACKUPS=3
      COMPRESS=y
