- name: Create press-crm network
  become: true
  docker_network:
    name: net-press-crm
    attachable: yes
    internal: yes

- name: start mysql container
  become: true
  docker_container:
    image: "mariadb:10.6"
    name: "press-crm-mysql"
    state: started
    restart_policy: always
    pull: True
    networks_cli_compatible: yes
    networks:
      - name: net-press-crm
    ulimits: nofile:4096:32768
    volumes:
      - /var/srv/mysql/press-crm:/var/lib/mysql:Z
    env:
      MYSQL_ROOT_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/mysql/root:value') }}"
      MYSQL_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/press-crm/mysql/password:value') }}"
      MYSQL_USER="press-crm"
      MYSQL_DATABASE="press-crm"
      MARIADB_AUTO_UPGRADE=1
      MARIADB_DISABLE_UPGRADE_BACKUP=1

- name: start second mysql container
  become: true
  docker_container:
    image: "mariadb:10.6"
    name: "press-crm-mysql-civi"
    state: started
    pull: True
    networks_cli_compatible: yes
    networks:
      - name: net-press-crm
    ulimits: nofile:4096:32768
    restart_policy: always
    volumes:
      - /var/srv/mysql/press-crm-civi:/var/lib/mysql:Z
    env:
      MYSQL_ROOT_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/mysql/root:value') }}"
      MYSQL_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/press-crm/mysql/password:value') }}"
      MYSQL_USER="press-crm"
      MYSQL_DATABASE="press-crm-civi"
      MARIADB_AUTO_UPGRADE=1
      MARIADB_DISABLE_UPGRADE_BACKUP=1

- name: start civicrm container
  become: true
  docker_container:
    image: "wordpress:php8.1"
    name: "press-crm"
    restart_policy: always
    labels:
     "traefik.enable": "true"
     "traefik.entryPoint": "https"
     "traefik.http.routers.presscivi.rule": "Host(`press-crm.piratenpartei.ch`)"
     "traefik.http.routers.presscivi.tls": "true"
     "traefik.http.routers.presscivi.tls.certresolver": "le"
     "traefik.http.routers.presscivi.middlewares": "security-headers@file"
    state: started
    pull: True
    networks_cli_compatible: yes
    networks:
      - name: net-proxy
      - name: net-press-crm
    volumes:
      - /var/srv/files/press-crm:/var/www/html:z
    env:
      WORDPRESS_DB_HOST="press-crm-mysql"
      WORDPRESS_DB_NAME="press-crm"
      WORDPRESS_DB_USER="press-crm"
      WORDPRESS_DB_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/press-crm/mysql/password:value') }}"

- name: start civicrm croncontainer
  become: true
  docker_container:
    image: "wordpress:cli-php8.1"
    name: "press-crm-cron"
    state: started
    pull: True
    networks_cli_compatible: yes
    networks:
      - name: net-press-crm
    restart_policy: always
    volumes:
      - /var/srv/files/press-crm:/var/www/html:z
    command: /var/www/html/startjobs.sh
    user: "33"
    env:
      WORDPRESS_DB_HOST="press-crm-mysql"
      WORDPRESS_DB_NAME="press-crm"
      WORDPRESS_DB_USER="press-crm"
      WORDPRESS_DB_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/press-crm/mysql/password:value') }}"

- name: start backup container for first mysql container
  become: true
  docker_container:
    image: yloeffler/mysql-backup
    name: "press-crm-backup"
    state: started
    restart_policy: always
    pull: True
    networks_cli_compatible: yes
    networks:
      - name: net-press-crm
    volumes:
      - /var/srv/mysql-backup/press-crm:/backup:Z
    env:
      MYSQL_HOST="press-crm-mysql"
      MYSQL_PORT=3306
      MYSQL_USER="press-crm"
      MYSQL_ENV_MYSQL_PASS="{{ lookup('hashi_vault', 'secret=secret/press-crm/mysql/password:value') }}"
      MAX_BACKUPS=3
      COMPRESS=y

- name: start backup container for second mysql container
  become: true
  docker_container:
    image: yloeffler/mysql-backup
    name: "press-crm-civi-backup"
    state: started
    restart_policy: always
    pull: True
    networks_cli_compatible: yes
    networks:
      - name: net-press-crm
    volumes:
      - /var/srv/mysql-backup/press-crm-civi:/backup:Z
    env:
      MYSQL_HOST="press-crm-mysql-civi"
      MYSQL_PORT=3306
      MYSQL_USER="press-crm"
      MYSQL_ENV_MYSQL_PASS="{{ lookup('hashi_vault', 'secret=secret/press-crm/mysql/password:value') }}"
      MAX_BACKUPS=3
      COMPRESS=y
