---
- name: api
  become: true
  docker_container:
    labels:
      "traefik.enable": "true"
      "traefik.entryPoint": "https"
      "traefik.http.routers.pirateapi.rule": "Host(`api.piratenpartei.ch`)"
      "traefik.http.routers.pirateapi.tls": "true"
      "traefik.http.routers.pirateapi.tls.certresolver": "le"
      "traefik.http.routers.pirateapi.middlewares": "security-headers@file"
    image: "ppschweiz/pps-api"
    name: "api"
    state: started
    pull: true
    networks_cli_compatible: true
    networks:
      - name: net-proxy
    restart_policy: always
    env:
      CIVICRM_SERVER=https://members-crm.piratenpartei.ch
      PPSAPI_SECRETS="{{ lookup('hashi_vault', 'secret=secret/api/PPSAPI_SECRETS:value') }}"
      STRIPE_SECRET_KEY="{{ lookup('hashi_vault', 'secret=secret/api/STRIPE_SECRET_KEY:value') }}"
      BITPAY_PRIVKEY="{{ lookup('hashi_vault', 'secret=secret/api/BITPAY_PRIVKEY:value') }}"
      CIVICRM_SITE_KEY="{{ lookup('hashi_vault', 'secret=secret/api/CIVICRM_SITE_KEY:value') }}"
      CIVICRM_API_KEY="{{ lookup('hashi_vault', 'secret=secret/api/CIVICRM_API_KEY:value') }}"
      PPSAPI_BASEURL=https://api.piratenpartei.ch/api/v1
      PPSAPI_PAYLINKURL=https://www.piratenpartei.ch
      BITPAY_MODE=prod
      LATEX_URL="http://sharelatex:81"
      PPSAPI_URL="https://api.piratenpartei.ch"
      PPSAPI_PAYSECRET="{{ lookup('hashi_vault', 'secret=secret/api/PPSAPI_PAYSECRET:value') }}"
      PPSAPI_INVOICESECRET="{{ lookup('hashi_vault', 'secret=secret/api/PPSAPI_INVOICESECRET:value') }}"
