- name: Create Redmine network
  become: true
  docker_network:
    name: net-redmine
    attachable: yes
    internal: yes

- name: start mariadb container
  become: true
  docker_container:
    image: "mariadb:10.6"
    name: "projects-mariadb"
    state: started
    restart_policy: always
    pull: True
    networks_cli_compatible: yes
    networks:
      - name: net-redmine
    ulimits: nofile:4096:32768
    volumes:
      - /var/srv/mysql/projects:/var/lib/mysql:Z
    env:
      MARIADB_RANDOM_ROOT_PASSWORD="true"
      MYSQL_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/projects/mysql/password:value') }}"
      MYSQL_USER="projects"
      MYSQL_DATABASE="projects"
      MARIADB_AUTO_UPGRADE=1
      MARIADB_DISABLE_UPGRADE_BACKUP=1

- name: Redmine mail config
  become: true
  template:
    src: templates/redmine.yml.j2
    dest: /var/srv/files/projects/configuration.yml
    mode: '0644'

- name: start projects/redmine container
  become: true
  docker_container:
    image: ghcr.io/ppschweiz/docker-redmine:master
    name: "projects"
    restart_policy: always
    labels:
     "traefik.enable": "true"
     "traefik.entryPoint": "https"
     "traefik.http.routers.redmine.rule": "Host(`projects.piratenpartei.ch`)"
     "traefik.http.routers.redmine.tls": "true"
     "traefik.http.routers.redmine.tls.certresolver": "le"
     "traefik.http.routers.redmine.middlewares": "security-headers@file"
    state: started
    pull: True
    networks_cli_compatible: yes
    networks:
      - name: net-proxy
      - name: net-redmine
    volumes:
      - /var/srv/files/projects/configuration.yml:/usr/src/redmine/config/configuration.yml:ro,Z
      - /var/srv/files/projects/files:/usr/src/redmine/files:Z
      - /var/srv/files/projects/themes/PurpleMine2:/usr/src/redmine/public/themes/PurpleMine2:ro,Z
    env:
      REDMINE_DB_DATABASE="projects"
      REDMINE_DB_MYSQL="projects-mariadb"
      REDMINE_DB_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/projects/mysql/password:value') }}"
      REDMINE_DB_USERNAME="projects"
      REDMINE_PLUGINS_MIGRATE=true

- name: start backup container for first mariadb container
  become: true
  docker_container:
    image: yloeffler/mysql-backup
    name: "projects-backup"
    state: started
    restart_policy: always
    pull: True
    networks_cli_compatible: yes
    networks:
      - name: net-redmine
    volumes:
      - /var/srv/mysql-backup/projects:/backup:Z
    env:
      MYSQL_HOST="projects-mariadb"
      MYSQL_PORT=3306
      MYSQL_USER="projects"
      MYSQL_ENV_MYSQL_PASS="{{ lookup('hashi_vault', 'secret=secret/projects/mysql/password:value') }}"
      MAX_BACKUPS=3
      COMPRESS=y
