     - name: start mysql container
       docker_container:
         image: "mysql:5"
         name: "projects-mysql"
         state: started
         restart_policy: always
         pull: True
         volumes:
           - /data/mysql/projects:/var/lib/mysql
         env:
           MYSQL_RANDOM_ROOT_PASSWORD="true"
           MYSQL_ONETIME_PASSWORD="true"
           MYSQL_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/projects/mysql/password:value') }}"
           MYSQL_USER="projects"
           MYSQL_DATABASE="projects"

     - name: Redmine mail config
       become: true
       copy:
         src: files/redmine.yml
         dest: /data/files/projects/configuration.yml

     - name: start projects/redmine container
       docker_container:
         image: ppschweiz/redmine
         name: "projects"
         restart_policy: always
         labels:
          "traefik.enable": "true"
         state: started
         pull: True
         links:
           - projects-mysql:mysql
         volumes:
           - /data/files/projects/configuration.yml:/usr/src/redmine/config/configuration.yml:ro
           - /data/files/projects/files:/usr/src/redmine/files
           - /data/files/projects/plugins:/usr/src/redmine/plugins:ro
           - /data/files/projects/themes:/usr/src/redmine/themes:ro
         env:
           REDMINE_DB_DATABASE="projects"
           REDMINE_DB_MYSQL="mysql"
           REDMINE_DB_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/projects/mysql/password:value') }}"
           REDMINE_DB_USERNAME="projects"
           REDMINE_PLUGINS_MIGRATE=true

     - name: start backup container for first mysql container
       docker_container:
         image: yloeffler/mysql-backup
         name: "projects-backup"
         state: started
         restart_policy: always
         pull: True
         links:
           - projects-mysql:mysql
         volumes:
           - /data/mysql-backup/projects/:/backup
         env:
           MYSQL_PASS="{{ lookup('hashi_vault', 'secret=secret/projects/mysql/password:value') }}"
           MAX_BACKUPS=3
           COMPRESS=y
