name: Ansible Lint
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@v4.1.0
        with:
          targets: "ansible/playbook.yaml"
          args: "-x 204" # Lines should be no longer than 160 chars
